# Generated by Django 4.2.4 on 2023-10-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_product_barcode'),
    ]

    operations = [
    ]
