# Generated by Django 4.2.4 on 2023-11-06 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mammal',
            old_name='for_color',
            new_name='fur_color',
        ),
    ]
