# Generated by Django 4.2.4 on 2023-11-14 14:19

from django.db import migrations, models
import main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='genre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[main_app.validators.validator_rating]),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='release_year',
            field=models.IntegerField(validators=[main_app.validators.validator_release_year]),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
